name: Surge PR Preview

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
  pull_request_target:
    types: [ closed ]

jobs:
  preview:
    runs-on: ubuntu-20.04
    if: github.event.pull_request_target || (github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success')
    steps:
      - name: Download PR Artifact
        uses: dawidd6/action-download-artifact@v2
        if: github.event.workflow_run && github.event.workflow_run.type == 'completed'
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          workflow_conclusion: success
          name: site
      - uses: afc163/surge-preview@v1
        id: preview_step
        with:
          surge_token: ${{ secrets.SURGE_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dist: site
          failOnError: 'true'
          teardown: 'true'
          build: |
            echo Deploying to surge.sh
      - name: Get the preview_url
        run: echo "url => ${{ steps.preview_step.outputs.preview_url }}"
